/* גוש וחלקה — split-screen viewer for Israel's cadastre and planning layers.
 *
 * Map half: OSM base + govmap WMS overlays of the selected layers (image tiles,
 * so no CORS issue). Clicking the map queries that point; the floating button
 * queries the device's current location.
 * Info half: scrollable cards with everything govmap returns for the point,
 * per selected layer, via the entitiesByPoint API — CORS-enabled, but requires
 * x-trace-id/x-user-id/x-fingerprint-id headers to be present (any value passes).
 * Offline fallback (Gush/Helka only): local 2km grid tiles in data/tiles/,
 * generated by download_data.py from govmap's WFS (which has no CORS headers).
 * All server coordinates and geometries are EPSG:3857 meters.
 */
const GEOSERVER = 'https://www.govmap.gov.il/api/geoserver/ows/public/';
const ENTITIES_API = 'https://www.govmap.gov.il/api/layers-catalog/entitiesByPoint';
const TILE_SIZE = 2000;
const R = 20037508.342789244; // Web-Mercator half-circumference

// Queryable govmap layers (ids and WMS names from the layers-catalog API).
// Listed bottom-to-top in WMS drawing order.
const LAYERS = [
  { id: '21', name: 'sub_gush_all', caption: 'גושים', wms: 'govmap:layer_sub_gush_all', on: true },
  { id: '15', name: 'parcel_all', caption: 'חלקות', wms: 'govmap:layer_parcel_all', on: true },
  { id: '6', name: 'parcel_ownership_new', caption: 'סוג בעלות בחלקות רשומות', wms: 'govmap:layer_parcel_ownership_new', on: false },
  { id: '357', name: 'retzefgvulot', caption: 'רצף גבולות תב"ע - רמ"י', wms: 'govmap:layer_retzefgvulot', on: false },
  { id: '11', name: 'retzefmigrashim', caption: 'רצף מגרשי תב"ע - רמ"י', wms: 'govmap:layer_retzefmigrashim', on: false },
  { id: '203', name: 'mehoziot_app_taba', caption: 'קווים כחולים - מבא"ת', wms: 'govmap:layer_mehoziot_app_taba', on: false },
  { id: '14', name: 'mehoziot_app_yk', caption: 'יעודי קרקע - מבא"ת', wms: 'govmap:layer_mehoziot_app_yk', on: false },
];

// Restore layer selection from a previous visit
try {
  const saved = JSON.parse(localStorage.getItem('taba-layers') || '{}');
  for (const l of LAYERS) if (l.id in saved) l.on = saved[l.id];
} catch (e) {
  console.error('failed to restore layer selection', e);
}

const map = L.map('map').setView([31.78, 35.21], 15);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
  maxZoom: 19,
  attribution: '&copy; OpenStreetMap | govmap.gov.il',
}).addTo(map);

let wmsLayer = null;

/** (Re)build the WMS overlay from the currently checked layers. */
function updateWms() {
  const active = LAYERS.filter(l => l.on).map(l => l.wms).join(',');
  if (wmsLayer) { wmsLayer.remove(); wmsLayer = null; }
  if (!active) return;
  wmsLayer = L.tileLayer.wms(GEOSERVER, {
    layers: active,
    styles: active,
    format: 'image/png',
    transparent: true,
    version: '1.3.0',
    maxZoom: 19,
    opacity: 0.8,
  }).addTo(map);
}
updateWms();

// Layer picker checkboxes
const layerList = document.getElementById('layer-list');
for (const l of LAYERS) {
  const label = document.createElement('label');
  const cb = Object.assign(document.createElement('input'), { type: 'checkbox', checked: l.on });
  cb.onchange = () => {
    l.on = cb.checked;
    localStorage.setItem('taba-layers', JSON.stringify(Object.fromEntries(LAYERS.map(x => [x.id, x.on]))));
    updateWms();
  };
  label.append(cb, ' ' + l.caption);
  layerList.append(label);
}

/** lat/lng (WGS84) -> EPSG:3857 meters. */
function toMercator(lat, lng) {
  return {
    x: lng * R / 180,
    y: Math.log(Math.tan((90 + lat) * Math.PI / 360)) / Math.PI * R,
  };
}

/** EPSG:3857 meters -> [lat, lng], for drawing server geometries on the map. */
function fromMercator(x, y) {
  return [Math.atan(Math.exp(y / R * Math.PI)) * 360 / Math.PI - 90, x / R * 180];
}

function toast(msg) {
  const el = document.getElementById('toast');
  el.textContent = msg;
  el.hidden = false;
  clearTimeout(toast.timer);
  toast.timer = setTimeout(() => { el.hidden = true; }, 5000);
  console.error(msg);
}

// Nothing that escapes a try/catch goes unreported
window.addEventListener('error', e => toast('שגיאה: ' + e.message));
window.addEventListener('unhandledrejection', e => toast('שגיאה: ' + (e.reason?.message || e.reason)));

// --- Geolocation tracking ---
// ?mocklat=..&mocklng=.. simulates a position (used by automated tests)
const urlParams = new URLSearchParams(location.search);
const mockPos = urlParams.has('mocklat')
  ? { lat: +urlParams.get('mocklat'), lng: +urlParams.get('mocklng') } : null;

let lastPos = null; // {lat, lng}
let centered = false;
const posMarker = L.circleMarker([0, 0], { radius: 8, color: '#fff', weight: 2, fillColor: '#1565c0', fillOpacity: 1 });
const accCircle = L.circle([0, 0], { radius: 0, color: '#1565c0', weight: 1, fillOpacity: 0.1 });

function onPosition(lat, lng, accuracy) {
  lastPos = { lat, lng };
  posMarker.setLatLng(lastPos);
  accCircle.setLatLng(lastPos).setRadius(accuracy);
  if (!posMarker._map) { posMarker.addTo(map); accCircle.addTo(map); }
  if (!centered) { centered = true; map.setView(lastPos, 17); }
}

if (mockPos) {
  setTimeout(() => onPosition(mockPos.lat, mockPos.lng, 12), 100);
} else if (!navigator.geolocation) {
  toast('הדפדפן לא תומך באיתור מיקום');
} else {
  navigator.geolocation.watchPosition(
    pos => onPosition(pos.coords.latitude, pos.coords.longitude, pos.coords.accuracy),
    err => toast('שגיאת מיקום: ' + err.message),
    { enableHighAccuracy: true, maximumAge: 5000 });
}

document.getElementById('locate-btn').onclick = () => {
  if (lastPos) map.setView(lastPos, 17);
  else toast('עדיין אין מיקום');
};

// --- Geometry helpers ---

/** Even-odd point-in-polygon over all rings (outer + holes) of a GeoJSON (Multi)Polygon. */
function containsPoint(geom, x, y) {
  const polys = geom.type === 'MultiPolygon' ? geom.coordinates : [geom.coordinates];
  return polys.some(rings => {
    let inside = false;
    for (const ring of rings) {
      for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
        const [xi, yi] = ring[i], [xj, yj] = ring[j];
        if ((yi > y) !== (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi) inside = !inside;
      }
    }
    return inside;
  });
}

function parseRing(s) {
  return s.split(',').map(pt => pt.trim().split(/\s+/).map(Number));
}

/** WKT POLYGON/MULTIPOLYGON (as returned by entitiesByPoint) -> GeoJSON-style geometry. */
function wktToMultiPolygon(wkt) {
  if (wkt.startsWith('MULTIPOLYGON')) {
    const inner = wkt.slice(wkt.indexOf('(((') + 3, wkt.lastIndexOf(')))'));
    return { type: 'MultiPolygon', coordinates: inner.split(')),((').map(p => p.split('),(').map(parseRing)) };
  }
  if (wkt.startsWith('POLYGON')) {
    const inner = wkt.slice(wkt.indexOf('((') + 2, wkt.lastIndexOf('))'));
    return { type: 'MultiPolygon', coordinates: [inner.split('),(').map(parseRing)] };
  }
  throw new Error('unsupported WKT: ' + wkt.slice(0, 40));
}

let highlight = null;
let highlightBtn = null;

/** Toggle the orange boundary of a (Multi)Polygon geometry on the map. */
function toggleHighlight(geom, btn) {
  const same = btn === highlightBtn;
  if (highlight) { highlight.remove(); highlight = null; }
  if (highlightBtn) { highlightBtn.classList.remove('active'); highlightBtn = null; }
  if (same) return;
  const latlngs = geom.coordinates.map(rings => rings.map(ring => ring.map(([x, y]) => fromMercator(x, y))));
  highlight = L.polygon(latlngs, { color: '#e65100', weight: 3, fillOpacity: 0.08 }).addTo(map);
  map.fitBounds(highlight.getBounds());
  highlightBtn = btn;
  btn.classList.add('active');
}

// --- Point queries ---
const results = document.getElementById('results');
const queryMarker = L.marker([0, 0]);
const tileCache = new Map(); // "ix_iy" -> parsed tile JSON (or null for missing)
const hex32 = () => [...crypto.getRandomValues(new Uint8Array(16))].map(b => b.toString(16).padStart(2, '0')).join('');

/** Live query of all checked layers via govmap's entitiesByPoint. */
async function queryLive(x, y) {
  const layers = LAYERS.filter(l => l.on).map(l => ({ layerId: l.id }));
  // ~3px tolerance at the current zoom, like govmap itself
  const tolerance = 3 * 156543.03392 / 2 ** map.getZoom();
  const res = await fetch(ENTITIES_API, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-trace-id': hex32(), 'x-user-id': hex32(), 'x-fingerprint-id': hex32(),
    },
    body: JSON.stringify({ point: [x, y], layers, tolerance }),
  });
  if (!res.ok) throw new Error(`entitiesByPoint HTTP ${res.status}`);
  const { data, error } = await res.json();
  if (error) throw new Error(`entitiesByPoint: ${error}`);
  return data || [];
}

/** Fetch (and cache) the 2km data tile containing mercator point (x, y). */
async function getTile(x, y) {
  const key = `${Math.floor(x / TILE_SIZE)}_${Math.floor(y / TILE_SIZE)}`;
  if (!tileCache.has(key)) {
    const res = await fetch(`data/tiles/${key}.json`);
    if (res.status === 404) {
      tileCache.set(key, null); // area with no cadastre data
    } else if (!res.ok) {
      throw new Error(`tile ${key}: HTTP ${res.status}`);
    } else {
      tileCache.set(key, await res.json());
    }
  }
  return tileCache.get(key);
}

/** Offline fallback: Gush/Helka from the local tiles, shaped like entitiesByPoint output. */
async function queryLocal(x, y) {
  const tile = await getTile(x, y);
  const ent = (rec, fields) => rec && {
    geom: rec.geom,
    fields: Object.entries(fields).map(([fieldName, fieldValue]) => ({ fieldName, fieldValue, isVisible: true })),
  };
  const parcel = tile?.parcels.find(p => containsPoint(p.geom, x, y));
  const gush = tile?.gushim.find(g => containsPoint(g.geom, x, y));
  return [
    { caption: 'גושים', entities: [ent(gush, gush && { 'מספר גוש': gush.gush_num, 'תת גוש': gush.gush_suffix, 'סטטוס': gush.status_text })].filter(Boolean) },
    { caption: 'חלקות', entities: [ent(parcel, parcel && { 'מספר גוש': parcel.gush_num, 'תת גוש': parcel.gush_suffix, 'חלקה': parcel.parcel, 'שטח רשום (מ"ר)': parcel.legal_area, 'סטטוס': parcel.status_text })].filter(Boolean) },
  ];
}

/** Format a field value for display: links, ISO dates, numbers.
 * Thousands separators only on area fields — gush/parcel/plan numbers are identifiers. */
function formatValue(v, fieldName) {
  if (v === null || v === undefined || v === '') return '—';
  if (typeof v === 'string' && /^https?:\/\//.test(v)) {
    const a = document.createElement('a');
    a.href = v; a.target = '_blank'; a.rel = 'noopener'; a.textContent = 'קישור';
    return a;
  }
  if (typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(v)) {
    return new Date(v).toLocaleDateString('he-IL');
  }
  if (typeof v === 'number' && /שטח/.test(fieldName)) return v.toLocaleString('he-IL');
  return String(v);
}

/** Render entitiesByPoint-shaped results into the info pane. */
function renderResults(layers, note) {
  results.replaceChildren();
  if (note) {
    const div = document.createElement('div');
    div.className = 'offline-note';
    div.textContent = note;
    results.append(div);
  }
  let any = false;
  for (const layer of layers) {
    const ents = layer.entities || [];
    if (!ents.length) continue;
    any = true;
    const card = document.createElement('div');
    card.className = 'layer-card';
    const h = document.createElement('h3');
    h.textContent = layer.caption + (ents.length > 1 ? ` (${ents.length})` : '');
    card.append(h);
    for (const ent of ents) {
      const div = document.createElement('div');
      div.className = 'entity';
      const head = document.createElement('div');
      head.className = 'entity-head';
      const btn = document.createElement('button');
      btn.textContent = 'הצג גבול';
      btn.onclick = () => {
        try {
          // WKT is parsed lazily: plan geometries can be 100KB+ each
          ent.parsed ??= typeof ent.geom === 'string' ? wktToMultiPolygon(ent.geom) : ent.geom;
          toggleHighlight(ent.parsed, btn);
        } catch (e) {
          console.error('highlight failed', e);
          toast('לא ניתן להציג את הגבול');
        }
      };
      head.append(btn);
      div.append(head);
      const table = document.createElement('table');
      for (const f of ent.fields) {
        if (!f.isVisible) continue;
        const tr = table.insertRow();
        tr.insertCell().textContent = f.fieldName;
        tr.insertCell().append(formatValue(f.fieldValue, f.fieldName));
      }
      div.append(table);
      card.append(div);
    }
    results.append(card);
  }
  if (!any) {
    const p = document.createElement('p');
    p.className = 'hint';
    p.textContent = 'לא נמצא מידע בשכבות שנבחרו עבור מיקום זה.';
    results.append(p);
  }
}

/** Query a map location and fill the info pane. */
async function queryPoint(latlng) {
  if (highlight) { highlight.remove(); highlight = null; highlightBtn = null; }
  queryMarker.setLatLng(latlng);
  if (!queryMarker._map) queryMarker.addTo(map);
  results.replaceChildren(Object.assign(document.createElement('p'), { className: 'hint', textContent: 'טוען…' }));
  const { x, y } = toMercator(latlng.lat, latlng.lng);
  try {
    renderResults(await queryLive(x, y));
  } catch (e) {
    console.error('live query failed, falling back to local Gush/Helka tiles', e);
    try {
      renderResults(await queryLocal(x, y), `השליפה החיה מ-govmap נכשלה (${e.message}) — מוצגים נתוני גוש/חלקה מקומיים בלבד`);
    } catch (e2) {
      console.error('local fallback failed too', e2);
      toast('שגיאה בשליפת מידע: ' + e2.message);
      results.replaceChildren(Object.assign(document.createElement('p'), { className: 'hint', textContent: 'שגיאה בשליפת המידע.' }));
    }
  }
}

map.on('click', e => queryPoint(e.latlng));

document.getElementById('here-btn').onclick = () => {
  if (!lastPos) { toast('עדיין אין מיקום — ודאו שאיתור מיקום מאושר'); return; }
  map.setView(lastPos);
  queryPoint(lastPos);
};
